name: bookshare
description: "Bookshare, a platform for book exchange and donation."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  skeletonizer: ^1.4.2
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ">=8.0.0 <10.0.0"
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/bookshare_app.png
    - assets/img/icons/book.png
    - assets/img/img/default_book_image.png
    - assets/img/img/default_user_image.png
