name: bookshare
description: "Bookshare, a platform for book exchange and donation."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ">=8.0.0 <10.0.0"
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
